### ISSUE TITLE
tabs.create()でのopenerTabIdの明示

### ISSUE THREAD

**Issue by piroor** [akahuku/akahukuplus#1]
リンクをタブで開く際に、現在のタブのIDを[`openerTabId`](https://developer.chrome.com/extensions/tabs#property-Tab-openerTabId)で明示するようにしていただくことは可能でしょうか？

拙作Firefox用アドオンTree Style Tab https://addons.mozilla.org/firefox/addon/tree-style-tab/ （リンクから開かれたタブを子として扱う、といった要領でタブをツリー形式で管理する物です）について、赤福プラスから開かれたタブが「子タブ」にならないという障害報告を受けました。
調査した結果、赤福プラス側で`tabs.create()`を呼ぶ際に`openerTabId`が指定されていないために、タブの親子関係を識別するヒントを得られていないという状況であることが分かりました。

`openerTabId`自体は特段それまでの動作を壊す性質の物ではありませんが、指定した場合、このプロパティに対応していない環境（Firefox 56以前）でエラーになるというデメリットがあります。
ただ、Firefox 56は既に公式にサポートが終了しているため、大きな問題にはならないのではないかと考えられます。
いかがでしょうか。

**Comment by akahuku** [comment]
ありがとうございます。次のリリースで取り込みます。
